version: "3.8"

services:
  webserver:
    build:
      context: . # De root directory waarvan Docker de build context zal nemen (inclusief alle benodigde bestanden).
      dockerfile: Dockerfile # Het specifieke Dockerfile dat gebruikt wordt voor het bouwen van het image, relatief aan de context.
    ports:
      - "8000:80" # De poort waarop de webserver luistert
    volumes:
      - .:/var/www/html # De directory waar de broncode zich bevindt
      - ./db:/var/www/html/db # De directory waar de database zich bevindt
      - ./apache-config:/etc/apache2/conf-available # De directory waar de Apache configuratie zich bevindt
    restart: always # De opstartoptie voor de container
    container_name: villa_verkenner_php # De naam van de container
    working_dir: /var/www/html # De directory waar de werkmap zich bevindt

volumes:
  db_data: # De volume waar de database zich bevindt
