version: '3.8'

services:
  webserver:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./db:/var/www/html/db
      - ./apache-config:/etc/apache2/conf-available
    restart: always
    container_name: villa_verkenner_php
    working_dir: /var/www/html

volumes:
  db_data:
